version: '3.9'
services:
  tests:
    image: {{cookiecutter.project_name}}:tests
    build:
      context: .
      dockerfile: Dockerfile
      target: tests
    volumes:
      - ./app:/{{cookiecutter.project_name}}/app
      - ./tests:/{{cookiecutter.project_name}}/tests
      - ./reports:/{{cookiecutter.project_name}}/reports
    environment:
      - STAGE=tests{% if cookiecutter.add_mongo_support == 'y' -%}
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:4.4.16
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/dev --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
{% endif %}
