name: Lock dependencies

on:
  workflow_dispatch:
    branches-ignore:
      - main
      - master

jobs:
  lock_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup python"
        uses: actions/setup-python@v4
        with:
          python-version: '{{ cookiecutter.python_version }}'

      - name: "Install uv"
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: "uv lock"
        run: |
          uv lock

      - name: "Commit new lock file"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci: Update lock file"
          commit_user_name: "Lock BOT"
          commit_user_email: "lock_bot@gmail.com"
          file_pattern: uv.lock
