name: Lock dependencies

on:
  workflow_dispatch:
    branches-ignore:
      - main
      - master

jobs:
  lock_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup python"
        uses: actions/setup-python@v4
        with:
          python-version: '{{ cookiecutter.python_version }}'

      - name: "Install Poetry"
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version {{cookiecutter.poetry_version}} && \
          export PATH="/root/.local/bin:$PATH"

      - name: "Poetry lock"
        run: |
          poetry lock

      - name: "Commit new lock file"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci: Update lock file"
          commit_user_name: "Lock BOT"
          commit_user_email: "lock_bot@gmail.com"
          file_pattern: poetry.lock
